image:
  pullPolicy: IfNotPresent
  pullSecrets:
    enabled: false
    secretName:


credentials:
  root:
    user: root
#    password: sakila
    host: "%"

tls:
  useSelfSigned: false
#  caSecretName:
#  serverCertAndPKsecretName:
#  routerCertAndPKsecretName:

#serverVersion: 8.0.30
serverInstances: 3
routerInstances: 1
baseServerId: 1000


#serverConfig:
#  mycnf: |
#    [mysqld]
#    core_file
#    local_infile=off


#datadirVolumeClaimTemplate:
#  accessModes:
#  resources:
#    requests:
#      storage:

#initDB:
#  dump:
#    name:
#    path:
#    options:
#      includeSchemas:
#    ociObjectStorage:
#      prefix:
#      bucketName:
#      credentials:
#    persistentVolumeClaim:
#  clone:
#    donorUrl:
#    rootUser:
#    credentials:


#backupProfiles:
#- name: dump-instance-profile-pvc
#  dumpInstance:
#    dumpOptions:
#      excludeSchemas: ["excludeme"]
#    storage:
#      persistentVolumeClaim:
#        claimName: backup-volume-claim-1
#- name: dump-instance-profile-oci
#  dumpInstance:
#    dumpOptions:
#      excludeSchemas: ["excludeme"]
#    storage:
#      ociObjectStorage:
#        prefix : /
#        bucketName: idbcluster_backup
#        credentials: oci-credentials
#
#- name: snapshot-profile-oci
#  snapshot:
#    storage:
#      ociObjectStorage:
#        prefix : /
#        bucketName: idbcluster_backup
#        credentials: oci-credentials

#backupSchedules:
#- name: schedule-ref
#  schedule: "*/1 * * * *"
#  deleteBackupData: false
#  backupProfileName: dump-instance-profile-oci
#  enabled: true
#- name: schedule-inline
#  schedule: "*/1 * * * *"
#  deleteBackupData: false
#  enabled: true
#  backupProfile:
#    dumpInstance:
#      dumpOptions:
#        excludeSchemas: ["excludeme"]
#      storage:
#        ociObjectStorage:
#          prefix : /
#          bucketName: idbcluster_backup
#          credentials: oci-credentials
